### ISSUE TITLE
unit tests failing

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#161]
latest from master fails unit tests

```python
======================================================================
ERROR: test_trivial_vector_gp (t_geometric_program.t_GP_cvxopt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 31, in test_trivial_vector_gp
    sol = prob.solve(printing=False)['variables']
  File "gpkit/geometric_program.py", line 341, in solve
    solution.append(self.__run_solver())
  File "gpkit/geometric_program.py", line 478, in __run_solver
    units = descr.pop("units")
KeyError: 'units'

======================================================================
ERROR: test_trivial_vector_gp (t_geometric_program.t_GP_mosek)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 31, in test_trivial_vector_gp
    sol = prob.solve(printing=False)['variables']
  File "gpkit/geometric_program.py", line 341, in solve
    solution.append(self.__run_solver())
  File "gpkit/geometric_program.py", line 478, in __run_solver
    units = descr.pop("units")
KeyError: 'units'

======================================================================
ERROR: test_trivial_vector_gp (t_geometric_program.t_GP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 31, in test_trivial_vector_gp
    sol = prob.solve(printing=False)['variables']
  File "gpkit/geometric_program.py", line 341, in solve
    solution.append(self.__run_solver())
  File "gpkit/geometric_program.py", line 478, in __run_solver
    units = descr.pop("units")
KeyError: 'units'

======================================================================
ERROR: test_call_vector (t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_gp_solution_array.py", line 20, in test_call_vector
    sol = prob.solve(printing=False)
  File "gpkit/geometric_program.py", line 341, in solve
    solution.append(self.__run_solver())
  File "gpkit/geometric_program.py", line 478, in __run_solver
    units = descr.pop("units")
KeyError: 'units'

======================================================================
FAIL: test_init (t_vars.t_VectorVariable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_vars.py", line 77, in test_init
    self.assertEqual(type(v), VectorVariable)
AssertionError: <class 'gpkit.posyarray.PosyArray'> != <class 'gpkit.nomials.VectorVariable'>

----------------------------------------------------------------------
Ran 47 tests in 1.305s

FAILED (failures=1, errors=4)
```

**Comment by bqpd** [comment]
Fixed by 6d560402d0efe7c8afa436f7040f17d1ff9e94a0
