### ISSUE TITLE
unit tests are failing

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#183]
and I can't sleep at night

```
======================================================================
FAIL: test_MOO (t_geometric_program.t_GP_cvxopt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 118, in test_MOO
    self.assertTrue((abs(a-b)/(a+b+1e-7) < 1e-7).all())
AssertionError: False is not true

======================================================================
FAIL: test_MOO (t_geometric_program.t_GP_mosek)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 118, in test_MOO
    self.assertTrue((abs(a-b)/(a+b+1e-7) < 1e-7).all())
AssertionError: False is not true

======================================================================
FAIL: test_MOO (t_geometric_program.t_GP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 118, in test_MOO
    self.assertTrue((abs(a-b)/(a+b+1e-7) < 1e-7).all())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 67 tests in 2.961s

FAILED (failures=3)

######################################################################
Running with units disabled:
......................................F......F......F..............
======================================================================
FAIL: test_MOO (t_geometric_program.t_GP_cvxopt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 118, in test_MOO
    self.assertTrue((abs(a-b)/(a+b+1e-7) < 1e-7).all())
AssertionError: False is not true

======================================================================
FAIL: test_MOO (t_geometric_program.t_GP_mosek)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 118, in test_MOO
    self.assertTrue((abs(a-b)/(a+b+1e-7) < 1e-7).all())
AssertionError: False is not true

======================================================================
FAIL: test_MOO (t_geometric_program.t_GP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 118, in test_MOO
    self.assertTrue((abs(a-b)/(a+b+1e-7) < 1e-7).all())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 67 tests in 2.142s

FAILED (failures=3)
```

**Comment by bqpd** [comment]
Whoops forgot to push those fixes this morning. :p

**Comment by whoburg** [comment]
Still failing for me.

**Comment by bqpd** [comment]
Ack, try now?

**Comment by whoburg** [comment]
Fixed
