### ISSUE TITLE
Test output confusing when build script not run

### ISSUE THREAD

**Issue by galbramc** [convexopt/gpkit#192]
Cosmetic issue: if the tests are run without running the build script, the variable "solver" is just a blank, leading to confusing `ValueError`s.

```
git clone ...
cd gpkit
"Do not run python setup.py build"
python -c 'import gpkit.tests; gpkit.tests.run()'
```

```
Running tests...
----------------------------------------------------------------------
....EEE...............................EEE
======================================================================
ERROR [0.002s]: test_VectorInit (gpkit.tests.t_sub.t_GPSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 94, in test_VectorInit
    sol = gp.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.001s]: test_VectorSweep (gpkit.tests.t_sub.t_GPSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 70, in test_VectorSweep
    a = gp.solve(printing=False)["cost"]
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.034s]: test_simpleaircraft (gpkit.tests.t_sub.t_GPSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 200, in test_simpleaircraft
    a = sorted_solve_array(sf.solve(printing=False))
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.000s]: test_call (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_gp_solution_array.py", line 13, in test_call
    sol = prob.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.051s]: test_call_time (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_gp_solution_array.py", line 38, in test_call_time
    sol = prob.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.003s]: test_call_vector (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_gp_solution_array.py", line 21, in test_call_vector
    sol = prob.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

----------------------------------------------------------------------
Ran 41 tests in 0.157s

FAILED (errors=6)

Generating XML reports...

Running tests...
----------------------------------------------------------------------
....EEE...............................EEE
======================================================================
ERROR [0.002s]: test_VectorInit (gpkit.tests.t_sub.t_GPSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 94, in test_VectorInit
    sol = gp.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.001s]: test_VectorSweep (gpkit.tests.t_sub.t_GPSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 70, in test_VectorSweep
    a = gp.solve(printing=False)["cost"]
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.032s]: test_simpleaircraft (gpkit.tests.t_sub.t_GPSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 200, in test_simpleaircraft
    a = sorted_solve_array(sf.solve(printing=False))
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.000s]: test_call (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_gp_solution_array.py", line 13, in test_call
    sol = prob.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.040s]: test_call_time (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_gp_solution_array.py", line 38, in test_call_time
    sol = prob.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

======================================================================
ERROR [0.002s]: test_call_vector (gpkit.tests.t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_gp_solution_array.py", line 21, in test_call_vector
    sol = prob.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 361, in _solve
    raise ValueError("Solver %s is not implemented!" % solver)
ValueError: Solver  is not implemented!

----------------------------------------------------------------------
Ran 41 tests in 0.131s
```

**Comment by bqpd** [comment]
Hi Marshall!

A couple potentially-dumb questions:
  - Did you install MOSEK or CVXopt?
  - Did you run build.py?

If you didn't do either, this is the expected if non-ideal response. The gp
tests check to see what solvers are installed (and skip themselves if none
are), it looks like t_sub and t_solution_array don't do that. If they did,
then these would pass too...

-Ned

**Comment by galbramc** [comment]
So this is the output you get if you do not run build.py. I also expect the failure, but the error messages "Solver  is not implemented!" are not particularly helpful in describing the problem. Both me and Woody think it would be better if the error message would elude to the fact that there is no solver and maybe the user forgot to run build.py or setup.py install.

**Comment by bqpd** [comment]
Hmm, good point. (worth noting that this only occurs when the user clones directly and doesn't follow the python convention of running `python setup.py` or installing via pip)

**Comment by galbramc** [comment]
Yes, but it does happen. Especially if it is someone who is new to python. It would just be good to have a more useful error message. I stumbled across it when I was trying to test when I had run python setup.py build in one clone of the repo, but I forgot to do it for the cloned repo jenkins was testing. 

Also, are you the one who put the sudo command in the build script? Someone really should remove that. It occurs as part of connecting with MOSEK. Not all users have sudo permissions in their computers. This is in fact the case for the jenkins user, and I can't test MOSEK right now because of the sudo command.

**Comment by bqpd** [comment]
Totally agree that we should have a more useful error message.

The sudo command is a hack because MOSEK on linux doesn't properly link its libraries. Feel free to link the libraries directly in the gcc command and make a pull request, or raise an issue on this topic; I'll take a look myself after adding this error message.

(using gcc explicitly is of course itself bad practice, as are the various additions to the users `~/.bashrc`)

**Comment by galbramc** [comment]
What are the mosek libraries you are trying to link to? You should just be able to use -L with the directory with the mosek libraries.

I also agree that you should not be adding things to the .bashrc file.

**Comment by bqpd** [comment]
We're adding the MOSEK libraries to the user's PATH, which is a fairly common hack (Anaconda does it, for instance) but it leaves a bad taste in my mouth.

**Comment by galbramc** [comment]
Yeah. I can appreciate the hack, but it only works if the user uses bash.

Looking at the mosek libraries, they seem to be all shared libraries. In that case I would expect adding mosek/7/tools/platform/linux64x86/bin/ to the LD_LIBRARY_PATH should be sufficient for the compiler/executable to find the libraries.

**Comment by bqpd** [comment]
I had troubles with that on linux.

**Comment by galbramc** [comment]
That's odd. Another solution is to add an rpath to the compiler arguments. That will explicitly add the path to the executable. Btw, are you compiling executables or shared libraries? The build gets stuck on the sudo command so I have not even seen the complete gcc command yet.

**Comment by galbramc** [comment]
So this works for me. For linux, you want to add the flags

"-Wl,--export-dynamic,-R" + self.bin_dir

on apple you want

"-Wl,-rpath " + self.bin_dir

and on cygwin

"-Wl,--export-all-symbols,-R" + self.bin_dir

This will add the path to the shared library instead. That way you will not need the sudo command or  add LD_LIBRARY_PATH to .bashrc.
