### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#211]
shoot, I broke master by being sloppy about units. fixing.

```python
======================================================================
ERROR: test_subinto_senssubinto (t_gp_solution_array.t_GPSolutionArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_gp_solution_array.py", line 64, in test_subinto_senssubinto
    self.assertEqual(Psol, sol(P_max))
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/unittest/case.py", line 503, in _baseAssertEqual
    if not first == second:
  File "gpkit/posyarray.py", line 97, in __eq__
    return PosyArray(self._eq(self, other))
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1688, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1751, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1713, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "gpkit/posyarray.py", line 85, in <lambda>
    _eq = np.vectorize(lambda a, b: a == b)
  File "gpkit/nomials.py", line 205, in __eq__
    return MonoEQConstraint(self, other)
  File "gpkit/nomials.py", line 460, in __init__
    "" % (p1.units.units, p2.units.units))
AttributeError: 'NoneType' object has no attribute 'units'

----------------------------------------------------------------------
Ran 70 tests in 3.522s

FAILED (errors=1)
```

**Comment by bqpd** [comment]
Looking forwards to the Jenkins emails about it.
