### ISSUE TITLE
make_feasibility_gp creates a dual infeasible gp when flavour=product

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#264]
```python
In [1]: %run gpkit/tests/run_tests.py
test_feasibility_gp_ (gpkit.tests.t_user_scripts.TestFeasibilityHelpers_product) ... ERROR
test_feasibility_gp_ (gpkit.tests.t_user_scripts.TestFeasibilityHelpers_max) ... ok
test_basic (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_scalar_units (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_string_mutation (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_vector (gpkit.tests.t_sub.TestNomialSubs) ... ok
test_simpleaircraft (gpkit.tests.t_sub.TestGPSubs) ... ok
test_vector_init (gpkit.tests.t_sub.TestGPSubs) ... ok
test_vector_sweep (gpkit.tests.t_sub.TestGPSubs) ... ok
test_dict_key (gpkit.tests.t_vars.TestVarKey) ... ok
test_eq_neq (gpkit.tests.t_vars.TestVarKey) ... ok
test_init (gpkit.tests.t_vars.TestVarKey) ... ok
test_repr (gpkit.tests.t_vars.TestVarKey) ... ok
test_init (gpkit.tests.t_vars.TestVariable) ... ok
test_value (gpkit.tests.t_vars.TestVariable) ... ok
test_init (gpkit.tests.t_vars.TestVectorVariable) ... ok
test_is_vector_variable (gpkit.tests.t_vars.TestArrayVariable) ... ok
test_str (gpkit.tests.t_vars.TestArrayVariable) ... ok
test_constraint_gen (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_diff (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_init (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_integer_division (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_monoapprox (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_posyposy_mult (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_simplification (gpkit.tests.t_nomials.TestPosynomial) ... ok
test_div (gpkit.tests.t_nomials.TestMonomial) ... ok
test_eq_ne (gpkit.tests.t_nomials.TestMonomial) ... ok
test_init (gpkit.tests.t_nomials.TestMonomial) ... ok
test_latex (gpkit.tests.t_nomials.TestMonomial) ... ok
test_mul (gpkit.tests.t_nomials.TestMonomial) ... ok
test_numerical_precision (gpkit.tests.t_nomials.TestMonomial) ... ok
test_pow (gpkit.tests.t_nomials.TestMonomial) ... ok
test_repr (gpkit.tests.t_nomials.TestMonomial) ... ok
test_init (gpkit.tests.t_nomials.TestSignomial) ... ok
test_additive_scalar (gpkit.tests.t_constraints.TestConstraint) ... ok
test_additive_scalar_gt1 (gpkit.tests.t_constraints.TestConstraint) ... ok
test_placeholder (gpkit.tests.t_constraints.TestMonoEQConstraint) ... ok
test_array_mult (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_constraint_gen (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_elementwise_mult (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_empty (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_getitem (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_left_right (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_ndim (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_outer (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_prod (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_shape (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_substition (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_sum (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_units (gpkit.tests.t_posy_array.TestPosyArray) ... ok
test_additive_constants (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_composite_objective (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_mdd_example (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_simpleflight (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_singular (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_trivial_gp (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_trivial_vector_gp (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_zeroing (gpkit.tests.t_geometric_program.TestGP_cvxopt) ... ok
test_additive_constants (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_composite_objective (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_mdd_example (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_simpleflight (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_singular (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_trivial_gp (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_trivial_vector_gp (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_zeroing (gpkit.tests.t_geometric_program.TestGP_mosek) ... ok
test_additive_constants (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_composite_objective (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_mdd_example (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_simpleflight (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_singular (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_trivial_gp (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_trivial_vector_gp (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_zeroing (gpkit.tests.t_geometric_program.TestGP_mosek_cli) ... ok
test_issue180 (gpkit.tests.t_geometric_program.TestSP_cvxopt) ... ok
test_sp_initial_guess_sub (gpkit.tests.t_geometric_program.TestSP_cvxopt) ... ok
test_trivial_sp (gpkit.tests.t_geometric_program.TestSP_cvxopt) ... ok
test_trivial_sp2 (gpkit.tests.t_geometric_program.TestSP_cvxopt) ... ok
test_issue180 (gpkit.tests.t_geometric_program.TestSP_mosek) ... ok
test_sp_initial_guess_sub (gpkit.tests.t_geometric_program.TestSP_mosek) ... ok
test_trivial_sp (gpkit.tests.t_geometric_program.TestSP_mosek) ... ok
test_trivial_sp2 (gpkit.tests.t_geometric_program.TestSP_mosek) ... ok
test_issue180 (gpkit.tests.t_geometric_program.TestSP_mosek_cli) ... ok
test_sp_initial_guess_sub (gpkit.tests.t_geometric_program.TestSP_mosek_cli) ... ok
test_trivial_sp (gpkit.tests.t_geometric_program.TestSP_mosek_cli) ... ok
test_trivial_sp2 (gpkit.tests.t_geometric_program.TestSP_mosek_cli) ... ok
test_call (gpkit.tests.t_gp_solution_array.TestGPSolutionArray) ... ok
test_call_time (gpkit.tests.t_gp_solution_array.TestGPSolutionArray) ... ok
test_call_vector (gpkit.tests.t_gp_solution_array.TestGPSolutionArray) ... ok
test_subinto_senssubinto (gpkit.tests.t_gp_solution_array.TestGPSolutionArray) ... ok
test_table (gpkit.tests.t_gp_solution_array.TestGPSolutionArray) ... ok

======================================================================
ERROR: test_feasibility_gp_ (gpkit.tests.t_user_scripts.TestFeasibilityHelpers_product)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_user_scripts.py", line 14, in test_feasibility_gp_
    sol1 = fgp.solve(printing=False)
  File "gpkit/geometric_program.py", line 335, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 385, in _solve
    solution.append(self._run_solver(allownonoptimal))
  File "gpkit/geometric_program.py", line 467, in _run_solver
    result = self.solverfn(c=cs, A=A, p_idxs=p_idxs, k=k)
  File "gpkit/_cvxopt.py", line 40, in cvxoptimize
    solution = gpsolver(k, F, g)
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/cvxprog.py", line 2162, in gp
    return cp(Fgp, G, h, dims, A, b)
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/cvxprog.py", line 1969, in cp
    xdot_e, xaxpy_e, xscal_e)
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/cvxprog.py", line 788, in cpl
    raise ValueError("Rank(A) < p or "\
ValueError: Rank(A) < p or Rank([H(x); A; Df(x); G]) < n

----------------------------------------------------------------------
Ran 91 tests in 7.163s

FAILED (errors=1)

######################################################################
Running with units disabled:
E..........................................................................................
======================================================================
ERROR: test_feasibility_gp_ (gpkit.tests.t_user_scripts.TestFeasibilityHelpers_product)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_user_scripts.py", line 14, in test_feasibility_gp_
    sol1 = fgp.solve(printing=False)
  File "gpkit/geometric_program.py", line 335, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 385, in _solve
    solution.append(self._run_solver(allownonoptimal))
  File "gpkit/geometric_program.py", line 479, in _run_solver
    cs, p_idxs, allownonoptimal)
  File "gpkit/geometric_program.py", line 495, in _parse_result
    + "\n\nTo find a feasible solution to"
RuntimeWarning: final status of solver 'cvxopt' was 'unknown' not 'optimal'

To find a feasible solution to a relaxed version of your gp, run gpkit.find_feasible_point(gp).

----------------------------------------------------------------------
Ran 91 tests in 6.192s

FAILED (errors=1)
```

**Comment by bqpd** [comment]
Oops. It works with MOSEK. How should we deal with this?

**Comment by whoburg** [comment]
It would fail with mosek if the constraints were `[x**2 >= 1, x <= 0.5]`.

I suspect this is happening because `make_feasibility_gp(flavour='product')` doesn't seem to constrain `\fbox >= 1`. Shouldn't it?

**Comment by whoburg** [comment]
PS -- remove the return statement in cfe19f2b928aff21ccfc5060de0724a623921e2f to test.

**Comment by bqpd** [comment]
Whoops, yeah, it should.

**Comment by bqpd** [comment]
Okay, now working with CVXOPT, but not with the MOSEK CLI

**Comment by bqpd** [comment]
oh, it's a MOSEK_CLI bug, fixing.

**Comment by whoburg** [comment]
huh, working for me with `mosek_cli`...

**Comment by bqpd** [comment]
huh! MOSEK_CLI was raising a ValueError instead of a RuntimeWarning for me during the first intentionally-failed solve.

**Comment by whoburg** [comment]
oh, gotcha. I don't think that was getting tested for me, since this test only gets run for the default installed solver.

Related to #258

**Comment by bqpd** [comment]
Yeah, I was changing my default solver by hand to check. Gross...

**Comment by bqpd** [comment]
On the other hand, though, this might just mean that we should wrap the solvers in a try/except that raises a RuntimeWarning, and let the solvers raise whatever issues they want...

**Comment by bqpd** [comment]
(@whoburg do you think we should do the try/except?)

**Comment by whoburg** [comment]
What would be the value of doing this? And would we still raise the original Exception from the solver? I tend to think it should be as transparent as possible what happened, at least as long as we're learning all the failure modes.
